name: Fetch Latest Tag

on: [push]

jobs:
  get-latest-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Fetch all tags
        run: git fetch --tags

      - name: Get the latest tag
        id: get_tag
        run: |
          # List all tags and sort them. Assuming tags are in semantic versioning format.
          latest_tag=$(git tag -l | sort -V | tail -n 1)
          echo "Latest tag: $latest_tag"
          echo "LATEST_TAG=$latest_tag" >> $GITHUB_ENV

      - name: Display the latest tag
        run: echo "The latest tag is ${{ env.LATEST_TAG }}"

      - name: Update package.json version
        run: |
          if [ -z "${{ env.LATEST_TAG }}" ]; then
            echo "No tags found, skipping version update."
            exit 1
          fi
          # Update package.json version
          npm version ${LATEST_TAG} --no-git-tag-version

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: anasrehmankhanllc
          author_email: anasrehmankhanllc@gmail.com
          message: 'initial'
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}

      - name: show the content of package.json
        run: cat package.json
