
name: on push
on:
  # workflow_dispatch:
  # push:
  #   tag:
  #     - '**'
    # branches:
    #   - main        

jobs:
  get-latest-tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}

      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.PAT }}
      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}

      - name: Fetch all tags
        run: git fetch --tags

      - name: Get the latest tag
        id: get_tag
        run: |
          # List all tags and sort them. Assuming tags are in semantic versioning format.
          latest_tag=$(git tag -l | sort -V | tail -n 1)
          echo "Latest tag: $latest_tag"
          echo "LATEST_TAG=$latest_tag" >> $GITHUB_ENV

      - name: Display the latest tag
        run: echo "The latest tag is ${{ env.LATEST_TAG }}"

      - name: Update package.json version
        run: |
          if [ -z "${{ env.LATEST_TAG }}" ]; then
            echo "No tags found, skipping version update."
            exit 1
          fi
          # Update package.json version
          npm version ${LATEST_TAG} --no-git-tag-version

      - name: show the content of package.json
        run: cat package.json

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: anasrehmankhanllc
          author_email: anasrehmankhanllc@gmail.com
          # message: 'bumping npm version'
          push: origin HEAD:main

  do-deployment:
    runs-on: ubuntu-latest
    needs: get-latest-tag
    steps:
      - name: deploy the app
        run: echo 'app is deployed with latest version'